services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: happynachbar
    ports:
      - "5433:5432" # nur f√ºr Zugriff vom Host
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d happynachbar"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./api
    ports:
      - "4000:4000"
    environment:
      API_PORT: 4000
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/happynachbar?schema=public"
      JWT_SECRET: "dev-super-secret-change-me"
      JWT_EXPIRES_IN: "1h"
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "npx prisma migrate deploy && node dist/src/main"]


  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: happynachbar-web
    depends_on:
      - api
    environment:
      NODE_ENV: production
      API_URL: http://api:4000

    ports:
      - "3000:3000"

volumes:
  db_data:
